### ISSUE TITLE
“do not use Fn2 for f because arrays pass in more arguments”

### ISSUE THREAD

**Issue by davidchambers** [gcanti/sanctuary-libdef#1]
I've never used Flow, but I'm intrigued by the comment in the snippet below:

> ```
>   declare interface Foldable<A> {
>     reduce<B>(f: (b: B, a: A) => B, b: B, ...rest: Array<void>): B; // <= do not use Fn2 for f because arrays pass in more arguments (currentIndex: number, array: Array<T>)
>   }
> ```

Why is the behaviour of `Array#map` germane? Sanctuary should be shielding us from such warts. :)

**Comment by gcanti** [comment]
It's not related to sanctuary, it's a Flow thing, `Fn2` is defined as

``` js
type Fn2<A, B, C> = (a: A, b: B, ...rest: Array<void>) => C;
```

the `...rest: Array<void>` part ensures arity `2`, but in the core definitions `Array#reduce` is defined as

``` js
reduce<U>(
  callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: Array<T>) => U,
  initialValue: U
): U;
```

`callbackfn` has arity `4` so there is a conflict. Using `(b: B, a: A) => B` allows for additional arguments.

**Comment by gcanti** [comment]
> I've never used Flow

Oh, by the way @davidchambers, you should give it a try, either Flow or TypeScript: doing functional programming with a type checker is way (_way_!) better ;)

**Comment by davidchambers** [comment]
Thanks for the information, @gcanti. I look forward to trying Sanctuary with Flow in the near future. :)
